apiVersion: v1
kind: Service 
metadata:
   name: cluster-redis-ip-service
spec:
   type: ClusterIP 
   selector:
      component: redis 
   ports:
      - port: 6379
        targetPort: 6379
        
