apiVersion: v1
kind: Service 
metadata:
   name: cluster-server-ip-service
spec:
   type: ClusterIP 
   selector:
      component: server
   ports:
      - Port: 5000
        targetPort: 5000
        